; Default configuration.

[settings]

; Nightlord IDs:
; 0=Gladius, 1=Adel, 2=Gnoster, 3=Maris, 4=Libra
; 5=Fulghor, 6=Caligo, 7=Heolstor, 8=Harmonia, 9=Straghess
; -1=Random
nightlord = -1

; 0=Normal, 1=Everdark, -1=Random
everdark = -1

; 32-bit integer (decimal or hexadecimal); -1 disables seed locking
seed = -1

log = 0
