#include "config.h"

#include <windows.h>

#include <iomanip>
#include <sstream>

namespace derandomizer {

std::string makeModConfig(std::uint32_t seed, int nightlord, int everdark) {
    // Heolstor (7) and Straghess (9) have no Everdark form. The DLL enforces
    // this policy too; normalising here keeps generated configs unambiguous.
    if (nightlord == 7 || nightlord == 9) everdark = 0;

    std::ostringstream content;
    content << "; Generated by Seed Reroller.\r\n\r\n"
            << "[settings]\r\n\r\n"
            << "; Nightlord IDs:\r\n"
            << "; 0=Gladius, 1=Adel, 2=Gnoster, 3=Maris, 4=Libra\r\n"
            << "; 5=Fulghor, 6=Caligo, 7=Heolstor, 8=Harmonia, 9=Straghess\r\n"
            << "nightlord = " << nightlord << "\r\n"
            << "everdark = " << everdark << "\r\n"
            << "seed = 0x" << std::uppercase << std::hex << std::setw(8)
            << std::setfill('0') << seed << std::dec << "\r\n"
            << "log = 0\r\n";
    return content.str();
}

bool writeModConfig(const std::filesystem::path& destination,
                    std::uint32_t seed,
                    int nightlord,
                    int everdark,
                    std::wstring& error) {
    if (destination.empty()) {
        error = L"The INI path is empty";
        return false;
    }

    const std::filesystem::path temporary = destination.wstring() + L".tmp";
    const std::string content = makeModConfig(seed, nightlord, everdark);
    const HANDLE file = CreateFileW(temporary.c_str(), GENERIC_WRITE, 0, nullptr,
                                    CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (file == INVALID_HANDLE_VALUE) {
        error = L"Could not create the temporary file (error " +
                std::to_wstring(GetLastError()) + L")";
        return false;
    }

    DWORD written = 0;
    const bool wrote = WriteFile(file, content.data(), static_cast<DWORD>(content.size()),
                                 &written, nullptr) &&
                       written == content.size() && FlushFileBuffers(file);
    const DWORD writeError = wrote ? ERROR_SUCCESS : GetLastError();
    CloseHandle(file);
    if (!wrote) {
        DeleteFileW(temporary.c_str());
        error = L"Could not write the INI file (error " +
                std::to_wstring(writeError) + L")";
        return false;
    }

    if (!MoveFileExW(temporary.c_str(), destination.c_str(),
                     MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH)) {
        const DWORD replaceError = GetLastError();
        DeleteFileW(temporary.c_str());
        error = L"Could not replace the INI file (error " +
                std::to_wstring(replaceError) + L")";
        return false;
    }
    return true;
}

}  // namespace derandomizer
